services:
  frontend:
    container_name: loopquest-frontend
    image: jinyuloopmind/loopquest-frontend:prod
    ports:
      # FUN FACT: The port 5667 means "LOOP" on the dial pad.
      - "5667:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    container_name: loopquest-backend
    image: jinyuloopmind/loopquest-backend:prod
    environment:
      # NOTE: This URL is the one exposed by the frontend container.
      - APP_URL=http://localhost:5667
    volumes:
      - media_store:/media
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    container_name: loopquest-mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db:/data/db

volumes:
  db:
  media_store:
