name: Loopquest Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  loopquest-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - name: Build the servers
        run: docker compose up -d --build
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -e .
          
      - name: Run pytest on tests folder
        run: pytest tests/
        
      - name: Stop Docker Compose
        run: docker-compose down
